# Generated by Django 4.2.6 on 2023-11-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('individual', 'Individual Account'), ('business', 'Business Account')], default='individual', max_length=20),
            preserve_default=False,
        ),
    ]
