# Generated by Django 4.2.6 on 2023-12-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='funds',
            field=models.IntegerField(default=0),
        ),
    ]
