# Generated by Django 4.2.6 on 2023-12-28 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_default_deliver_address_customuser_default_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='bank_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.bankaccount'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transaction', to='users.transaction'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='kind',
            field=models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund')], default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transaction', to='users.transaction'),
        ),
        migrations.CreateModel(
            name='FeeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.bankaccount')),
                ('transaction', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_transaction', to='users.transaction')),
            ],
        ),
    ]
