# Generated by Django 4.2.6 on 2023-12-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_transaction_amount_remove_transaction_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feetransaction',
            name='kind',
            field=models.CharField(choices=[('highlight_ad', 'Highlight Ad')], default=None, max_length=30),
            preserve_default=False,
        ),
    ]
