# Generated by Django 4.2.6 on 2023-12-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_feetransaction_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='kind',
            field=models.CharField(choices=[('bank_transaction', 'Bank Transaction'), ('payment_transaction', 'Payment Transaction'), ('fee_transaction', 'Fee Transaction')], default=None, max_length=20),
            preserve_default=False,
        ),
    ]
