# Generated by Django 4.2.6 on 2023-12-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_transaction_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='visible_to_users_by_pk',
            field=models.JSONField(default=list),
        ),
    ]
