# Generated by Django 4.2.6 on 2023-12-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_transaction_visible_to_users_by_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='visible_to_users_by_pk',
            field=models.JSONField(default=list, editable=False),
        ),
    ]
