# Generated by Django 4.2.6 on 2023-12-29 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_transaction_visible_to_users_by_pk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='visible_to_users_by_pk',
        ),
        migrations.AddField(
            model_name='transaction',
            name='visible_to',
            field=models.ManyToManyField(editable=False, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
