# Generated by Django 4.2.6 on 2023-12-29 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_rename_bank_account_banktransaction_source_bank_account_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banktransaction',
            old_name='source_bank_account',
            new_name='action_bank_account',
        ),
        migrations.RenameField(
            model_name='feetransaction',
            old_name='source_bank_account',
            new_name='action_bank_account',
        ),
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='source_bank_account',
            new_name='action_bank_account',
        ),
    ]
