# Generated by Django 4.2.6 on 2023-12-30 23:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_rename_source_bank_account_banktransaction_action_bank_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banktransaction',
            name='date',
        ),
        migrations.RemoveField(
            model_name='feetransaction',
            name='date',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='date',
        ),
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
