# Generated by Django 4.2.6 on 2024-01-18 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_remove_banktransaction_kind_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankTransaction',
            new_name='WithdrawalTransaction',
        ),
    ]
