# Generated by Django 4.2.6 on 2024-01-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_rename_banktransaction_withdrawaltransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='funds',
            field=models.FloatField(default=0),
        ),
    ]
