# Generated by Django 4.2.6 on 2024-01-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_ad_options'),
        ('users', '0024_alter_customuser_funds'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bookmarks',
            field=models.ManyToManyField(related_name='bookmarks', to='store.ad'),
        ),
    ]
