# Generated by Django 4.2.6 on 2024-02-06 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_order_seller_order_tracking_number'),
        ('users', '0025_customuser_bookmarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='receiver_bank_account',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='transations', to='store.order'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
