# Generated by Django 4.2.6 on 2024-02-07 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_remove_paymenttransaction_kind_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='funds',
            new_name='seller_funds',
        ),
    ]
