# Generated by Django 4.2.6 on 2023-11-15 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=4096)),
                ('price', models.IntegerField()),
                ('category', models.ForeignKey(limit_choices_to=models.Q(('subcategories', None)), on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
    ]
