# Generated by Django 4.2.6 on 2024-01-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_cartitem_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ads',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='amount',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='settings',
            field=models.JSONField(default=dict),
        ),
    ]
