# Generated by Django 4.2.6 on 2024-01-18 16:31

from django.db import migrations, models
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_cart_ads_remove_cartitem_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='settings',
        ),
        migrations.AddField(
            model_name='ad',
            name='specifications',
            field=models.JSONField(default=dict, validators=[store.validators.BasicJsonValidator]),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
