# Generated by Django 4.2.6 on 2024-01-18 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_cartitem_settings_ad_specifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ad',
            name='shipping',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
