# Generated by Django 4.2.6 on 2023-11-24 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_ad_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='images',
            field=models.JSONField(default=list),
        ),
    ]
