# Generated by Django 4.2.6 on 2024-01-27 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_adgroup_ad_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['-date_created']},
        ),
    ]
