# Generated by Django 4.2.6 on 2023-11-26 15:03

import datetime
from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_ad_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='expiry_date',
            field=models.DateTimeField(default=store.models.ad_default_expiry_date),
        ),
        migrations.AddField(
            model_name='ad',
            name='highlight_expiry',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
