# Generated by Django 4.2.6 on 2023-11-26 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_ad_expiry_date_ad_highlight_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='latest_push_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
