# Generated by Django 4.2.6 on 2024-02-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_alter_ad_group_alter_ad_specifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('pending_shipping', 'Pending Shipping'), ('shipped', 'Shipped'), ('arrived', 'Arrived'), ('completed', 'Completed'), ('pending_return', 'Pending Return'), ('returned', 'Returned')], default=None, max_length=40),
            preserve_default=False,
        ),
    ]
