# Generated by Django 4.2.6 on 2023-11-26 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_ad_latest_push_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['-latest_push_date']},
        ),
    ]
