# Generated by Django 4.2.6 on 2023-11-26 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_ad_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={},
        ),
    ]
