# Generated by Django 4.2.6 on 2024-02-01 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
