# Generated by Django 4.2.6 on 2024-02-03 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='store.ad'),
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='archive',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('pending_shipping', 'Pending Shipping'), ('shipped', 'Shipped'), ('arrived', 'Arrived'), ('completed', 'Completed'), ('pending_return', 'Pending Return'), ('returned', 'Returned'), ('canceled', 'Canceled')], max_length=40),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
