# Generated by Django 4.2.6 on 2023-12-31 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='gallery_expiry',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='ad',
            name='top_expiry',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
