# Generated by Django 4.2.6 on 2024-01-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_ad_gallery_expiry_ad_top_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='available',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('almost_new', 'Almost New'), ('used', 'Used'), ('damaged', 'Damaged')], max_length=30),
        ),
        migrations.AddField(
            model_name='ad',
            name='return_policy',
            field=models.CharField(choices=[('7_days', '7 Days Return Policy'), ('30_days', '30 Days Return Policy'), ('warranty', 'Warranty Period Policy')], default='7_days', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='shipping',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='unlisted',
            field=models.BooleanField(default=False),
        ),
    ]
