# Generated by Django 4.2.6 on 2024-01-10 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0013_ad_available_ad_condition_ad_return_policy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('visitor', 'Visitor Cart'), ('user', 'User Cart')], max_length=20)),
                ('ads', models.ManyToManyField(related_name='in_carts', to='store.ad')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
                ('visitor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='sessions.session')),
            ],
        ),
    ]
