# Generated by Django 4.2.6 on 2024-02-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_order_seller_order_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='archive',
            field=models.JSONField(default=dict),
        ),
    ]
