# Generated by Django 4.2.6 on 2024-02-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_ad_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='ad',
            name='shipping',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
