# Generated by Django 4.2.6 on 2024-02-14 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0027_rename_funds_customuser_seller_funds'),
        ('store', '0018_alter_order_options_ordercancellation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('pending_shipping', 'Pending Shipping'), ('shipped', 'Shipped'), ('arrived', 'Arrived'), ('completed', 'Completed'), ('pending_return', 'Pending Return'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], max_length=40),
        ),
        migrations.CreateModel(
            name='AdBoost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('gallery', 'Gallery Boost'), ('top', 'Top Boost'), ('highlight', 'Highlight Boost'), ('push', 'Push')], max_length=50)),
                ('amount', models.FloatField()),
                ('archive', models.JSONField(default=dict)),
                ('ad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boosts', to='store.ad')),
                ('bank_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.bankaccount')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
