# Generated by Django 4.2.6 on 2024-02-07 23:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_order_archive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.DecimalValidator(decimal_places=2, max_digits=50)])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('order_archive', models.JSONField(default=dict)),
                ('sender_archive', models.JSONField(default=dict)),
                ('receiver_archive', models.JSONField(default=dict)),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='store.order')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.DecimalValidator(decimal_places=2, max_digits=50)])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('archive', models.JSONField(default=dict)),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund', to='store.order')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='ordertransactionreceiver',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ordertransactionreceiver',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ordertransactionsender',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ordertransactionsender',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrderTransaction',
        ),
        migrations.DeleteModel(
            name='OrderTransactionReceiver',
        ),
        migrations.DeleteModel(
            name='OrderTransactionSender',
        ),
    ]
