# Generated by Django 4.2.6 on 2024-02-08 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_order_archive'),
        ('transactions', '0002_orderpayment_orderrefund_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpayment',
            name='order_archive',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='receiver_archive',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='sender_archive',
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='archive',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='store.order'),
        ),
        migrations.AlterField(
            model_name='orderrefund',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='store.order'),
        ),
    ]
