# Generated by Django 4.2.6 on 2024-02-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_orderpayment_amount_alter_orderrefund_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledgerentry',
            old_name='transaction_archive',
            new_name='transaction_data',
        ),
    ]
