# Generated by Django 4.2.6 on 2024-02-09 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_rename_transaction_archive_ledgerentry_transaction_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='kind',
            field=models.CharField(choices=[('order_transaction', 'Order Transaction')], max_length=30),
        ),
    ]
