# Generated by Django 4.2.6 on 2024-02-14 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_ledgerentry_date_created_alter_ledgerentry_kind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledgerentry',
            options={'ordering': ['-date_created']},
        ),
    ]
